### ISSUE TITLE
how to use the expiration time

### ISSUE THREAD

**Issue by jparadaa** [matteobaccan/HarbourJwt#20]
Hi Matteo,

I just discovered your JWT work for Harbour and I'm doing some tests, but there are some things I don't understand, I'm sure it's because of my lack of knowledge.

my test

oJWT := &("JWT():new()")

oJWT:setAlgorithm("HS256")
oJWT:setType("JWT")

// Payload
oJWT:setSubject("1234567890")
oJWT:setPayloadData("id", "my name")
oJWT:setPayloadData("exp" , 30)     // tiempo en segundos que expira el token
oJWT:setPayloadData("session" , "123045678901234567890")
oJWT:setIssuedAt(1516239022)

How can I verify the token and how do I use the expiration time, at this moment I always get it:

KO - invalid data
Value   : .F.
Expected: .T.
Token expired

Can you please help with a slightly clearer example for beginners?

Regards,
Javier

**Comment by matteobaccan** [comment]
Hi

I have add a new test for a more clear example

https://github.com/matteobaccan/HarbourJwt/blob/main/test/jwtcreate.prg

Tell me if now is more clear

ciao
matteo

**Comment by jparadaa** [comment]
I think it is very helpful, let me try to do some tests.

I appreciate your help.

Regards, 
Javier
